//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12
{
    using System;
    using System.Collections.Generic;
    
    public partial class duyurular
    {
        public short id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> YazarId { get; set; }
        public Nullable<System.DateTime> SonaErmeTarihi { get; set; }
        public Nullable<bool> Yayinda { get; set; }
        public string Resimyolu { get; set; }
        public string DosyaYolu { get; set; }
    
        public virtual users users { get; set; }
    }
}
