//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mezuntakipEntities : DbContext
    {
        public mezuntakipEntities()
            : base("name=mezuntakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<askerlikdurumlari> askerlikdurumlari { get; set; }
        public virtual DbSet<bolumler> bolumler { get; set; }
        public virtual DbSet<calismadurumlari> calismadurumlari { get; set; }
        public virtual DbSet<cinsiyetler> cinsiyetler { get; set; }
        public virtual DbSet<duyurular> duyurular { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<medenihaller> medenihaller { get; set; }
        public virtual DbSet<ogrenimturleri> ogrenimturleri { get; set; }
        public virtual DbSet<programlar> programlar { get; set; }
        public virtual DbSet<roller> roller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
